### ISSUE TITLE
Improve parser whitespace robustness

### ISSUE THREAD

**Issue by odanoburu** [EvgSkv/logica#130]
This predicate parses:

```
Human(name: "Socrates", iq: 250, year_of_birth: -470, location: "Athens");
```

but this one doesn't, because it contains a tab:

```
Human(name: "Socrates", iq: 250, year_of_birth: -470, location: "Athens"	);
```

(example inspired by the Logica Postgres quick start)

tested with

```
logica test.l print Human
```

where test.l has the contents of the source blocks above.

**EDIT**: I hadn't initially realized that the problem was solely caused by tabs.

**Comment by EvgSkv** [comment]
Thanks for pointing this out!
Indeed we need to include tab into set of _spaces_:
https://github.com/EvgSkv/logica/blob/main/parser_py/parse.py#L268
