### ISSUE TITLE
Blog post with examples

### ISSUE THREAD

**Issue by kpconnell** [EvgSkv/logica#33]
Whoever wrote the article here does not seem to understand databases much.  https://opensource.googleblog.com/2021/04/logica-organizing-your-data-queries.html

```
SELECT 2 AS x

UNION ALL

SELECT 3 AS x

UNION ALL

SELECT 5 AS x;

```
Would never happen.  You'd have a table of ints.

**Comment by EvgSkv** [comment]
I've edited the title.
Criticism is welcome. However please follow community guidelines and be respectful of others.

**Comment by EvgSkv** [comment]
In my opinion using self contained statements in tutorials is a good practice, as it allows reader to execute something and see results immediately.

Here this approach is used in BigQuery SQL tutorial:
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

**Comment by kpconnell** [comment]
EvgSkv You and your team have  provided examples that would never happen in the real world and it is very *very* clear from the project that there is a misunderstanding of the dichotomy between a set based  implementation (aka RDBMS) and  programming languages.  As a gesture of respect, I'm happy to turn any and all of your examples in that post into a more performant and concise implementation using any existing modern ORM and RDBMS implementation

**Comment by EvgSkv** [comment]
kpconnell, I am interested in your perspective on how to make the examples better. Your insights will surely be useful for delivering our message in the future. You are welcome to post your examples here, or even better in a new Discussion thread.
Thank you for reaching out.
