### ISSUE TITLE
Syntax highlighting in VSCode

### ISSUE THREAD

**Issue by EvgSkv** [EvgSkv/logica#35]
Just as subject says: We should make ".l" files have proper syntax highlighting in VSCode editor.

**Comment by EricWay1024** [comment]
I would like to work on this issue. I've noticed that we have a syntax highlighting configuration for vim, but it doesn't look complete enough as a grammar description. Do we have a formal description of the grammar of Logica yet?

**Comment by RAbraham** [comment]
@EricWay1024 just curious, are you planning to go the VS Code direct API route or the Language Server Protocol route(https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)

**Comment by EvgSkv** [comment]
@EricWay1024 This is awesome! I'll post a formal syntax description by the end of this work week.

**Comment by EricWay1024** [comment]
> @EricWay1024 just curious, are you planning to go the VS Code direct API route or the Language Server Protocol route(https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)

@RAbraham As this issue is only concerned with syntax highlighting which is a declarative language feature and is defined in configuration files, for now I plan to first work on writing Logica syntax in TextMate grammars (as is described [here](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide)). So at this stage I haven't considered which approach to take when developing programmatic language features. Any suggestions?

**Comment by EricWay1024** [comment]
> @EricWay1024 This is awesome! I'll post a formal syntax description by the end of this work week.

OK, thank you for your help.

**Comment by RAbraham** [comment]
@EricWay1024 textmate grammar sounds good!

re: programmatic language features. If you have the time and interest, the Language Server Protocol has the benefit that we do it once and we can reuse it across different editors(e.g. Vim, PyCharm and VSCode) and not just VSCode. On the flip side, it 'may' be more complex than the VS Code API.

Caveat, I haven't done this before but that would be the direction I would consider if I had the time to help.

**Comment by EvgSkv** [comment]
@EricWay1024, I've added a BNF syntax specification in `dev` branch:
https://github.com/EvgSkv/logica/blob/dev/docs/syntax.md

Let me know if you have any questions, or note any problems with it.

**Comment by EvgSkv** [comment]
Also, @EricWay1024 would you mind singing Google's CLA, so we can accept your contributions?
Please see https://github.com/EvgSkv/logica/blob/main/CONTRIBUTING.md for details.

**Comment by EricWay1024** [comment]
@EvgSkv Thank you for your work! I've signed Google's CLA now.

Should I create a new repo for this VS Code extension or put everything in some folder in this repo?

**Comment by EvgSkv** [comment]
Thanks for signing it, @EricWay1024!

I've moved the VIM files to a new `syntax` folder.
It would be great if you could put the VSCode files into a sub-folder of `syntax`.

I don't know how VSCode syntax highlighting works, but it looks like implementing the whole parsing there could take quite a bit of time. Having just basic highlighting of predicates/variables/numbers/strings/operators etc, like it's done in current VIM would definitely be a great start.

In anyway, thank you very much for looking into this! I am looking forward to using VSCode for my logical programs! :-)

**Comment by EricWay1024** [comment]
@EvgSkv OK, I see. I'll be working on the basic highlighting first. I'll submit a pull request once this is finished, hopefully in several days. :smiley:

**Comment by EvgSkv** [comment]
Thanks to @EricWay1024 work Syntax Highlighting is available in VS code!
Closing the issue as fixed!
