### ISSUE TITLE
Tables with no columns

### ISSUE THREAD

**Issue by mikko-ahonen** [EvgSkv/logica#362]
I get a following error:

[ Error ] Tables with no columns are not allowed in StandardSQL, so they are not allowed in Logica.

With approximately the following code (I simplified it a little bit for clarity).

If I define Goal as "Goal(true)", then it passes.

@Engine("sqlite");

@AttachDatabase("db", "db.sqlite3");

@Ground(Training, "db.training");
@Ground(TrainingOrganized, "db.trainingorganized");
@Ground(Employee, "db.employee");
@Ground(TrainingAttended, "db.trainingattended");
@Ground(Classification, "db.classification");

BasicTraining(id:id, name:name) :- Training(id:, name:), Classification(source_id:id, classification:"basic");

AttendedBasicTraining(e_id:) :-
    BasicTraining(id:t_id),
    TrainingAttended(e_id:e_id, training_id:t_id, date:d),
    d >= "2021-08-07";

EmployeeNotAttendedBasicTraining() :-
  Employee(id:e_id),
  ~AttendedBasicTraining(e_id:e_id);

CountNotAttendedBasicTraining(count? += 1) distinct :-
  EmployeeNotAttendedBasicTraining();

Goal() :-
  CountNotAttendedBasicTraining(count:),
  count > 0;

**Comment by EvgSkv** [comment]
That's right, as we compile to SQL it's technically impossible to produce a table with no columns, which formally `Goal` is.

Your workaround with `Goal(true)` is precisely what I'd recommend.

This is actually changed in the current version of the code already, but it wasn't pushed to pypi yet. If you run off of cloned repository then your code should work as is, and compiler uses a workaround just like yours, adding an unsed column `atom` with an unused value `yes` :-) This will get to pypi next time we publish a new verson there.

Example: https://colab.research.google.com/drive/1yWY82sfU70Bu9uzJ60B-Vsyi-9THit94?usp=sharing

Let me know if you have further questons!

And thank you very much for the feedback! We are working on the next iteration of documentation and will make sure to incorporate these hurdles that you are identifying.

**Comment by mikko-ahonen** [comment]
All right. It is understandable from SQL point of view but surprising from predicate logic point of view. But if it is already fixed then no problem :)
