### ISSUE TITLE
hi! he did work in big quary? 

### ISSUE THREAD

**Issue by kingtelepuz5** [EvgSkv/logica#56]
hi, I have a question, does it work in big guary and will it work in the future? I have not figured it out yet to test it, but if it really works in the google cloud console, I will definitely start testing it in the near future

**Comment by kingtelepuz5** [comment]
sorry, I didn't read the documentation in a hurry, please close this stupid question

**Comment by EvgSkv** [comment]
Closing issue.
But let me know if you have any new questions.

**Comment by kingtelepuz5** [comment]
Thanks for feedback
