### ISSUE TITLE
How to use logica in MacOS?

### ISSUE THREAD

**Issue by 180909** [EvgSkv/logica#65]
Thanks for everyone to create this project.
I want to learn logica, but i don't known how to install logica.
I visit the README.md file, install Google Cloud SDK and clone https://github.com/EvgSkv/logica.
But i don't know how to use logica to run file.
Thank your very much.

**Comment by EvgSkv** [comment]
Thank you very much for your interest!

Please try running the following commands in this order in your terminal:

```sh
git clone https://github.com/evgskv/logica
cd logica
./logica - print Greet <<<'Greet(greeting: "Hello world!")'
./logica - run Greet <<<'Greet(greeting: "Hello world!")'
echo 'Q("hello from file!")' > my_first_program.l
./logica my_first_program.l run Q
```

If you have Google Cloud SDK installed and configured then this should run the program from command line and from the file.

Let me know what results you get, I'll try to help you from there.

**Comment by 180909** [comment]
Thank you very much fro your reply.
I can run my_first_program.l file in my computer.
Thank you very much.
